'use client';

import { useState, useEffect } from 'react';
import { ArticleFormData, ArticleCategory } from '@/lib/types/articles';
import { generateSlug } from '@/lib/utils';

interface ArticleEditorProps {
  initialData?: Partial<ArticleFormData>;
  onSubmit: (data: ArticleFormData) => Promise<void>;
  isSubmitting?: boolean;
}

export default function ArticleEditor({
  initialData,
  onSubmit,
  isSubmitting = false,
}: ArticleEditorProps) {
  const [formData, setFormData] = useState<ArticleFormData>({
    title: initialData?.title || '',
    slug: initialData?.slug || '',
    category: initialData?.category || 'interview',
    content: initialData?.content || '',
    excerpt: initialData?.excerpt || '',
    featured_image_url: initialData?.featured_image_url || '',
    is_public: initialData?.is_public !== undefined ? initialData.is_public : false,
    published_at: initialData?.published_at || null,
    meta_title: initialData?.meta_title || '',
    meta_description: initialData?.meta_description || '',
  });

  const [slugAutoGenerated, setSlugAutoGenerated] = useState(false);

  // タイトルからスラッグを自動生成
  useEffect(() => {
    if (!initialData?.slug && formData.title && !slugAutoGenerated) {
      const generatedSlug = generateSlug(formData.title);
      setFormData((prev) => ({ ...prev, slug: generatedSlug }));
      setSlugAutoGenerated(true);
    }
  }, [formData.title, initialData?.slug, slugAutoGenerated]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onSubmit(formData);
  };

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value, type } = e.target;
    const checked = (e.target as HTMLInputElement).checked;

    if (name === 'title' && !slugAutoGenerated) {
      // タイトル変更時にスラッグも自動更新（手動編集していない場合）
      const generatedSlug = generateSlug(value);
      setFormData((prev) => ({
        ...prev,
        title: value,
        slug: generatedSlug,
      }));
    } else {
      setFormData((prev) => ({
        ...prev,
        [name]: type === 'checkbox' ? checked : value,
      }));
    }

    // スラッグを手動編集した場合、自動生成フラグを解除
    if (name === 'slug') {
      setSlugAutoGenerated(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <label htmlFor="title" className="block text-sm font-medium text-gray-700 mb-1">
          タイトル <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="title"
          name="title"
          value={formData.title}
          onChange={handleChange}
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
        />
      </div>

      <div>
        <label htmlFor="slug" className="block text-sm font-medium text-gray-700 mb-1">
          スラッグ <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="slug"
          name="slug"
          value={formData.slug}
          onChange={handleChange}
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
        />
        <p className="mt-1 text-sm text-gray-500">
          URLに使用されるスラッグ（例: article-title）
        </p>
      </div>

      <div>
        <label htmlFor="category" className="block text-sm font-medium text-gray-700 mb-1">
          カテゴリ <span className="text-red-500">*</span>
        </label>
        <select
          id="category"
          name="category"
          value={formData.category}
          onChange={handleChange}
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
        >
          <option value="interview">リアル体験談 クチコミ・インタビュー</option>
          <option value="useful_info">通信制高校お役立ち情報</option>
        </select>
      </div>

      <div>
        <label htmlFor="excerpt" className="block text-sm font-medium text-gray-700 mb-1">
          抜粋
        </label>
        <textarea
          id="excerpt"
          name="excerpt"
          value={formData.excerpt}
          onChange={handleChange}
          rows={3}
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
          placeholder="記事の抜粋文を入力してください（一覧表示で使用されます）"
        />
      </div>

      <div>
        <label htmlFor="content" className="block text-sm font-medium text-gray-700 mb-1">
          本文（Markdown）
        </label>
        <textarea
          id="content"
          name="content"
          value={formData.content}
          onChange={handleChange}
          rows={15}
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 font-mono text-sm"
          placeholder="# 見出し1&#10;&#10;本文を入力してください..."
        />
        <p className="mt-1 text-sm text-gray-500">
          Markdown形式で入力してください
        </p>
      </div>

      <div>
        <label htmlFor="featured_image_url" className="block text-sm font-medium text-gray-700 mb-1">
          アイキャッチ画像URL
        </label>
        <input
          type="url"
          id="featured_image_url"
          name="featured_image_url"
          value={formData.featured_image_url}
          onChange={handleChange}
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
          placeholder="https://example.com/image.jpg"
        />
      </div>

      <div className="flex items-center">
        <input
          type="checkbox"
          id="is_public"
          name="is_public"
          checked={formData.is_public}
          onChange={handleChange}
          className="w-4 h-4 text-orange-600 border-gray-300 rounded focus:ring-orange-500"
        />
        <label htmlFor="is_public" className="ml-2 text-sm font-medium text-gray-700">
          公開する
        </label>
      </div>

      <div className="border-t border-gray-200 pt-6">
        <h3 className="text-lg font-medium text-gray-900 mb-4">SEO設定</h3>

        <div className="mb-4">
          <label htmlFor="meta_title" className="block text-sm font-medium text-gray-700 mb-1">
            メタタイトル
          </label>
          <input
            type="text"
            id="meta_title"
            name="meta_title"
            value={formData.meta_title}
            onChange={handleChange}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
            placeholder="SEO用のタイトル（未指定の場合はタイトルが使用されます）"
          />
        </div>

        <div>
          <label htmlFor="meta_description" className="block text-sm font-medium text-gray-700 mb-1">
            メタ説明
          </label>
          <textarea
            id="meta_description"
            name="meta_description"
            value={formData.meta_description}
            onChange={handleChange}
            rows={3}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
            placeholder="SEO用の説明文（未指定の場合は抜粋が使用されます）"
          />
        </div>
      </div>

      <div className="flex justify-end gap-4 pt-4">
        <button
          type="submit"
          disabled={isSubmitting}
          className="px-6 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? '保存中...' : '保存'}
        </button>
      </div>
    </form>
  );
}


