'use client';

import { useState } from 'react';
import { SchoolFormData } from '@/lib/types/schools';
import { generateSlug } from '@/lib/utils';
import { prefectures } from '@/lib/prefectures';
import JsonArrayEditor from './JsonArrayEditor';
import JsonObjectArrayEditor from './JsonObjectArrayEditor';

interface SchoolEditorProps {
  initialData?: Partial<SchoolFormData>;
  onSubmit: (data: SchoolFormData) => Promise<void>;
  isSubmitting?: boolean;
}

export default function SchoolEditor({
  initialData,
  onSubmit,
  isSubmitting = false,
}: SchoolEditorProps) {
  const [formData, setFormData] = useState<SchoolFormData>({
    name: initialData?.name || '',
    prefecture: initialData?.prefecture || '',
    slug: initialData?.slug || '',
    intro: initialData?.intro || '',
    highlights: initialData?.highlights || [],
    faq: initialData?.faq || [],
    is_public: initialData?.is_public !== undefined ? initialData.is_public : true,
  });

  const [slugAutoGenerated, setSlugAutoGenerated] = useState(false);

  // 学校名からスラッグを自動生成
  const handleNameChange = (value: string) => {
    setFormData((prev) => {
      const newSlug = !slugAutoGenerated && prev.slug === initialData?.slug
        ? generateSlug(value)
        : prev.slug;
      return {
        ...prev,
        name: value,
        slug: newSlug,
      };
    });
  };

  const handleSlugChange = (value: string) => {
    setFormData((prev) => ({ ...prev, slug: value }));
    setSlugAutoGenerated(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
          学校名 <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="name"
          name="name"
          value={formData.name}
          onChange={(e) => handleNameChange(e.target.value)}
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
        />
      </div>

      <div>
        <label htmlFor="prefecture" className="block text-sm font-medium text-gray-700 mb-1">
          都道府県 <span className="text-red-500">*</span>
        </label>
        <select
          id="prefecture"
          name="prefecture"
          value={formData.prefecture}
          onChange={(e) => setFormData((prev) => ({ ...prev, prefecture: e.target.value }))}
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
        >
          <option value="">選択してください</option>
          {prefectures.map((pref) => (
            <option key={pref} value={pref}>
              {pref}
            </option>
          ))}
        </select>
      </div>

      <div>
        <label htmlFor="slug" className="block text-sm font-medium text-gray-700 mb-1">
          スラッグ <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="slug"
          name="slug"
          value={formData.slug}
          onChange={(e) => handleSlugChange(e.target.value)}
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
        />
        <p className="mt-1 text-sm text-gray-500">
          URLに使用されるスラッグ（例: school-name）
        </p>
      </div>

      <div>
        <label htmlFor="intro" className="block text-sm font-medium text-gray-700 mb-1">
          紹介文
        </label>
        <textarea
          id="intro"
          name="intro"
          value={formData.intro}
          onChange={(e) => setFormData((prev) => ({ ...prev, intro: e.target.value }))}
          rows={6}
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
          placeholder="学校の紹介文を入力してください"
        />
      </div>

      <div>
        <JsonArrayEditor
          label="特徴・推しポイント"
          items={formData.highlights}
          onChange={(items) => setFormData((prev) => ({ ...prev, highlights: items }))}
          placeholder="特徴を入力"
        />
      </div>

      <div>
        <JsonObjectArrayEditor
          label="FAQ"
          items={formData.faq}
          onChange={(items) => setFormData((prev) => ({ ...prev, faq: items }))}
          keyLabel="質問"
          valueLabel="回答"
        />
      </div>

      <div className="flex items-center">
        <input
          type="checkbox"
          id="is_public"
          name="is_public"
          checked={formData.is_public}
          onChange={(e) =>
            setFormData((prev) => ({ ...prev, is_public: e.target.checked }))
          }
          className="w-4 h-4 text-orange-600 border-gray-300 rounded focus:ring-orange-500"
        />
        <label htmlFor="is_public" className="ml-2 text-sm font-medium text-gray-700">
          公開する
        </label>
      </div>

      <div className="flex justify-end gap-4 pt-4">
        <button
          type="submit"
          disabled={isSubmitting}
          className="px-6 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? '保存中...' : '保存'}
        </button>
      </div>
    </form>
  );
}


