'use client';

import { useState } from 'react';
import {
  getCampusNearestStationSlots,
  insertCampusLocationByPrefecture,
  moveCampusLocation,
  sortCampusLocationsByPrefecture,
  updateCampusLocationPrefecture,
} from '@/lib/schools/campusLocations';
import { SchoolFormData } from '@/lib/types/schools';
import { generateSlug } from '@/lib/utils';
import { prefectures } from '@/lib/prefectures';
import { apiPath } from '@/lib/base-path';
import JsonArrayEditor from './JsonArrayEditor';
import JsonObjectArrayEditor from './JsonObjectArrayEditor';

interface SchoolEditorProps {
  initialData?: Partial<SchoolFormData>;
  onSubmit: (data: SchoolFormData) => Promise<void>;
  isSubmitting?: boolean;
  /** 学校ID（指定時のみ「AIで生成」ボタンを表示） */
  schoolId?: string;
  /** 公式URLが人間確認済みか（false=AI推定など未確認の注意表示） */
  officialUrlVerified?: boolean;
  /** 公式URLの取得元（ai=AI推定の注意表示用） */
  officialUrlSource?: string | null;
}

export default function SchoolEditor({
  initialData,
  onSubmit,
  isSubmitting = false,
  schoolId,
  officialUrlVerified = true,
  officialUrlSource = null,
}: SchoolEditorProps) {
  const [generatingIntro, setGeneratingIntro] = useState(false);
  const [formData, setFormData] = useState<SchoolFormData>({
    name: initialData?.name || '',
    prefecture: initialData?.prefecture || '',
    prefectures: initialData?.prefectures || (initialData?.prefecture ? [initialData.prefecture] : []),
    institution_type: initialData?.institution_type || '',
    campus_locations: initialData?.campus_locations || [],
    slug: initialData?.slug || '',
    intro: initialData?.intro || '',
    highlights: initialData?.highlights || [],
    faq: initialData?.faq || [],
    official_url: initialData?.official_url || '',
    is_public: initialData?.is_public !== undefined ? initialData.is_public : true,
  });

  const [slugAutoGenerated, setSlugAutoGenerated] = useState(false);

  // 学校名からスラッグを自動生成
  const handleNameChange = (value: string) => {
    setFormData((prev) => {
      const newSlug = !slugAutoGenerated && prev.slug === initialData?.slug
        ? generateSlug(value)
        : prev.slug;
      return {
        ...prev,
        name: value,
        slug: newSlug,
      };
    });
  };

  const handleSlugChange = (value: string) => {
    setFormData((prev) => ({ ...prev, slug: value }));
    setSlugAutoGenerated(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
          学校名 <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="name"
          name="name"
          value={formData.name}
          onChange={(e) => handleNameChange(e.target.value)}
          autoComplete="organization"
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label htmlFor="prefecture" className="block text-sm font-medium text-gray-700 mb-1">
          都道府県（メイン） <span className="text-red-500">*</span>
        </label>
        <select
          id="prefecture"
          name="prefecture"
          value={formData.prefecture}
          onChange={(e) => {
            const newPrefecture = e.target.value;
            const newPrefectures = formData.prefectures || [];
            // メイン都道府県がprefectures配列に含まれていない場合は追加
            if (newPrefecture && !newPrefectures.includes(newPrefecture)) {
              setFormData((prev) => ({
                ...prev,
                prefecture: newPrefecture,
                prefectures: [...newPrefectures, newPrefecture],
              }));
            } else {
              setFormData((prev) => ({ ...prev, prefecture: newPrefecture }));
            }
          }}
          autoComplete="address-level1"
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="">選択してください</option>
          {prefectures.map((pref) => (
            <option key={pref} value={pref}>
              {pref}
            </option>
          ))}
        </select>
      </div>

      <fieldset>
        <legend className="block text-sm font-medium text-gray-700 mb-1">
          都道府県（複数選択可）
        </legend>
        <div className="space-y-2 max-h-60 overflow-y-auto border border-gray-300 rounded-lg p-3">
          {prefectures.map((pref) => {
            const isSelected = formData.prefectures?.includes(pref) || false;
            return (
              <label key={pref} htmlFor={`prefecture-${pref}`} className="flex items-center">
                <input
                  id={`prefecture-${pref}`}
                  name={`prefecture-${pref}`}
                  type="checkbox"
                  checked={isSelected}
                  onChange={(e) => {
                    const currentPrefectures = formData.prefectures || [];
                    if (e.target.checked) {
                      // 追加
                      const newPrefectures = [...currentPrefectures, pref];
                      setFormData((prev) => ({
                        ...prev,
                        prefectures: newPrefectures,
                        // 最初の都道府県をメインに設定（まだ設定されていない場合）
                        prefecture: prev.prefecture || pref,
                      }));
                    } else {
                      // 削除
                      const newPrefectures = currentPrefectures.filter((p) => p !== pref);
                      setFormData((prev) => ({
                        ...prev,
                        prefectures: newPrefectures,
                        // メイン都道府県が削除された場合、最初の要素をメインに設定
                        prefecture: prev.prefecture === pref && newPrefectures.length > 0
                          ? newPrefectures[0]
                          : prev.prefecture,
                      }));
                    }
                  }}
                  className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                />
                <span className="ml-2 text-sm text-gray-700">{pref}</span>
              </label>
            );
          })}
        </div>
        <p className="mt-1 text-sm text-gray-500">
          選択された都道府県: {formData.prefectures?.length || 0}件
        </p>
      </fieldset>

      <div>
        <label htmlFor="institution_type" className="block text-sm font-medium text-gray-700 mb-1">
          設置区分
        </label>
        <select
          id="institution_type"
          name="institution_type"
          value={formData.institution_type}
          onChange={(e) =>
            setFormData((prev) => ({
              ...prev,
              institution_type: e.target.value as SchoolFormData['institution_type'],
            }))
          }
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="">未設定</option>
          <option value="public">公立通信制高校</option>
          <option value="private">私立通信制高校</option>
          <option value="support">サポート校</option>
        </select>
        <p className="mt-1 text-sm text-gray-500">
          都道府県ページで設置区分ごとの学校表示に使用します。
        </p>
      </div>

      <fieldset>
        <legend className="block text-sm font-medium text-gray-700 mb-2">
          キャンパス所在地（市区町村）
        </legend>
        <p className="text-sm text-gray-500 mb-3">
          都道府県ページや学校詳細で、市区町村・最寄り駅として表示します。同じ都道府県に複数キャンパスがある場合は複数追加してください。↑↓で表示順を変更でき、「都道府県でまとめる」で同じ都道府県を隣接させられます。
        </p>
        <div className="flex justify-end gap-2 mb-2">
          <button
            type="button"
            onClick={() =>
              setFormData((prev) => ({
                ...prev,
                campus_locations: sortCampusLocationsByPrefecture(
                  prev.campus_locations,
                  prefectures
                ),
              }))
            }
            disabled={formData.campus_locations.length < 2}
            className="px-3 py-1 text-sm border border-gray-300 rounded hover:bg-gray-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            都道府県でまとめる
          </button>
          <button
            type="button"
            onClick={() =>
              setFormData((prev) => ({
                ...prev,
                campus_locations: insertCampusLocationByPrefecture(
                  prev.campus_locations,
                  { prefecture: prev.prefecture || '', city: '', nearest_stations: [] },
                  prefectures
                ),
              }))
            }
            className="px-3 py-1 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
          >
            追加
          </button>
        </div>
        <div className="space-y-3">
          {formData.campus_locations.map((location, index) => {
            const [station1, station2] = getCampusNearestStationSlots(location);
            const previousPrefecture =
              index > 0 ? formData.campus_locations[index - 1].prefecture : null;
            const showPrefectureDivider =
              Boolean(location.prefecture) && location.prefecture !== previousPrefecture;
            return (
            <div key={index}>
              {showPrefectureDivider && (
                <div className="mb-2 pt-1 text-xs font-semibold text-gray-500">
                  {location.prefecture}
                </div>
              )}
            <div className="grid grid-cols-1 md:grid-cols-[1fr_1fr_1.4fr_auto] gap-2 items-end border border-gray-200 rounded-lg p-3">
              <div>
                <label htmlFor={`campus-location-prefecture-${index}`} className="block text-sm font-medium text-gray-700 mb-1">
                  都道府県
                </label>
                <select
                  id={`campus-location-prefecture-${index}`}
                  value={location.prefecture}
                  onChange={(e) => {
                    setFormData((prev) => ({
                      ...prev,
                      campus_locations: updateCampusLocationPrefecture(
                        prev.campus_locations,
                        index,
                        e.target.value,
                        prefectures
                      ),
                    }));
                  }}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">選択してください</option>
                  {prefectures.map((pref) => (
                    <option key={pref} value={pref}>
                      {pref}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label htmlFor={`campus-location-city-${index}`} className="block text-sm font-medium text-gray-700 mb-1">
                  市区町村
                </label>
                <input
                  id={`campus-location-city-${index}`}
                  type="text"
                  value={location.city}
                  onChange={(e) => {
                    const next = [...formData.campus_locations];
                    next[index] = { ...next[index], city: e.target.value };
                    setFormData((prev) => ({ ...prev, campus_locations: next }));
                  }}
                  placeholder="例: 新宿区"
                  autoComplete="address-level2"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div className="space-y-2">
                <div>
                  <label htmlFor={`campus-location-station-1-${index}`} className="block text-sm font-medium text-gray-700 mb-1">
                    最寄り駅（1）
                  </label>
                  <input
                    id={`campus-location-station-1-${index}`}
                    type="text"
                    value={station1}
                    onChange={(e) => {
                      const next = [...formData.campus_locations];
                      const [, second] = getCampusNearestStationSlots(next[index]);
                      const stations = [e.target.value, second].filter((value) => value.trim().length > 0);
                      next[index] = { ...next[index], nearest_stations: stations };
                      setFormData((prev) => ({ ...prev, campus_locations: next }));
                    }}
                    placeholder="例: JR山手線 新宿駅"
                    autoComplete="off"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <div>
                  <label htmlFor={`campus-location-station-2-${index}`} className="block text-sm font-medium text-gray-700 mb-1">
                    最寄り駅（2）
                  </label>
                  <input
                    id={`campus-location-station-2-${index}`}
                    type="text"
                    value={station2}
                    onChange={(e) => {
                      const next = [...formData.campus_locations];
                      const [first] = getCampusNearestStationSlots(next[index]);
                      const stations = [first, e.target.value].filter((value) => value.trim().length > 0);
                      next[index] = { ...next[index], nearest_stations: stations };
                      setFormData((prev) => ({ ...prev, campus_locations: next }));
                    }}
                    placeholder="例: 丸の内線 新宿三丁目駅（任意）"
                    autoComplete="off"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </div>
              <div className="flex gap-1">
                <button
                  type="button"
                  onClick={() =>
                    setFormData((prev) => ({
                      ...prev,
                      campus_locations: moveCampusLocation(prev.campus_locations, index, 'up'),
                    }))
                  }
                  disabled={index === 0}
                  className="px-2 py-2 text-sm border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                  aria-label="上に移動"
                >
                  ↑
                </button>
                <button
                  type="button"
                  onClick={() =>
                    setFormData((prev) => ({
                      ...prev,
                      campus_locations: moveCampusLocation(prev.campus_locations, index, 'down'),
                    }))
                  }
                  disabled={index === formData.campus_locations.length - 1}
                  className="px-2 py-2 text-sm border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                  aria-label="下に移動"
                >
                  ↓
                </button>
                <button
                  type="button"
                  onClick={() =>
                    setFormData((prev) => ({
                      ...prev,
                      campus_locations: prev.campus_locations.filter((_, i) => i !== index),
                    }))
                  }
                  className="px-3 py-2 text-sm text-red-600 border border-red-300 rounded-lg hover:bg-red-50"
                >
                  削除
                </button>
              </div>
            </div>
            </div>
          );
          })}
          {formData.campus_locations.length === 0 && (
            <p className="text-sm text-gray-500">所在地は未登録です。追加ボタンで登録できます。</p>
          )}
        </div>
      </fieldset>

      <div>
        <label htmlFor="slug" className="block text-sm font-medium text-gray-700 mb-1">
          スラッグ <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="slug"
          name="slug"
          value={formData.slug}
          onChange={(e) => handleSlugChange(e.target.value)}
          autoComplete="off"
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <p className="mt-1 text-sm text-gray-500">
          URLに使用されるスラッグ（例: school-name）
        </p>
      </div>

      <div>
        <div className="flex items-center justify-between gap-2 mb-1">
          <label htmlFor="intro" className="block text-sm font-medium text-gray-700">
            学校概要（紹介文）
          </label>
          {schoolId && (
            <button
              type="button"
              onClick={async () => {
                if (!confirm('公式サイトを検索して学校概要をAI生成しますか？\n（Perplexity API を使用します）')) {
                  return;
                }
                setGeneratingIntro(true);
                try {
                  const res = await fetch(apiPath(`/api/admin/schools/${schoolId}/intro/generate`), {
                    method: 'POST',
                    credentials: 'include',
                  });
                  if (!res.ok) {
                    const err = await res.json();
                    throw new Error(err.error || '生成に失敗しました');
                  }
                  const data = await res.json();
                  setFormData((prev) => ({ ...prev, intro: data.intro || '' }));
                  alert(`生成しました（使用トークン: ${data.tokensUsed?.total ?? '不明'}）`);
                } catch (e) {
                  alert(e instanceof Error ? e.message : '学校概要の生成に失敗しました');
                } finally {
                  setGeneratingIntro(false);
                }
              }}
              disabled={generatingIntro || isSubmitting}
              className="text-sm px-3 py-1.5 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {generatingIntro ? '生成中...' : 'AIで生成'}
            </button>
          )}
        </div>
        <textarea
          id="intro"
          name="intro"
          value={formData.intro}
          onChange={(e) => setFormData((prev) => ({ ...prev, intro: e.target.value }))}
          rows={6}
          autoComplete="off"
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="学校の紹介文を入力してください（AIで生成ボタンで公式サイトから要約を生成できます）"
        />
      </div>

      <div>
        <label htmlFor="official_url" className="block text-sm font-medium text-gray-700 mb-1">
          公式サイトURL
        </label>
        <input
          type="url"
          id="official_url"
          name="official_url"
          value={formData.official_url || ''}
          onChange={(e) => setFormData((prev) => ({ ...prev, official_url: e.target.value }))}
          placeholder="https://example.ac.jp/"
          autoComplete="url"
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        {formData.official_url && !officialUrlVerified && (
          <div className="mt-2 rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-800">
            <span className="font-semibold">
              {officialUrlSource === 'ai' ? 'AI推定・未確認のURLです' : '未確認のURLです'}
            </span>
            <br />
            このURLが正しい公式サイトか確認し、問題なければそのまま保存してください（保存すると確認済みになります）。誤っていれば正しいURLに直して保存してください。
          </div>
        )}
        <p className="mt-1 text-sm text-gray-500">
          学費・コース情報のAI抽出の起点として使用します（ユーザー向けページには表示されません）。
        </p>
      </div>

      <div>
        <JsonArrayEditor
          label="特徴・推しポイント"
          items={formData.highlights}
          onChange={(items) => setFormData((prev) => ({ ...prev, highlights: items }))}
          placeholder="特徴を入力"
        />
      </div>

      <div>
        <JsonObjectArrayEditor
          label="FAQ"
          items={formData.faq}
          onChange={(items) => setFormData((prev) => ({ ...prev, faq: items }))}
          keyLabel="質問"
          valueLabel="回答"
        />
      </div>

      <div className="flex items-center">
        <input
          type="checkbox"
          id="is_public"
          name="is_public"
          checked={formData.is_public}
          onChange={(e) =>
            setFormData((prev) => ({ ...prev, is_public: e.target.checked }))
          }
          className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
        />
        <label htmlFor="is_public" className="ml-2 text-sm font-medium text-gray-700">
          公開する
        </label>
      </div>

      <div className="flex justify-end gap-4 pt-4">
        <button
          type="submit"
          disabled={isSubmitting}
          className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? '保存中...' : '保存'}
        </button>
      </div>
    </form>
  );
}




