'use client';

import { useEffect, useState } from 'react';
import {
  getCampusNearestStationSlots,
  moveCampusLocation,
  sortCampusLocationsByPrefecture,
} from '@/lib/schools/campusLocations';
import { SchoolCampusLocation, SchoolFormData } from '@/lib/types/schools';
import { generateSlug } from '@/lib/utils';
import { prefectures } from '@/lib/prefectures';
import { apiPath } from '@/lib/base-path';
import JsonArrayEditor from './JsonArrayEditor';
import JsonObjectArrayEditor from './JsonObjectArrayEditor';

interface SchoolEditorProps {
  initialData?: Partial<SchoolFormData>;
  onSubmit: (data: SchoolFormData) => Promise<void>;
  isSubmitting?: boolean;
  /** 学校ID（指定時のみ「AIで生成」ボタンを表示） */
  schoolId?: string;
  /** 公式URLが人間確認済みか（false=AI推定など未確認の注意表示） */
  officialUrlVerified?: boolean;
  /** 公式URLの取得元（ai=AI推定の注意表示用） */
  officialUrlSource?: string | null;
}

const EMPTY_CAMPUS_LOCATION: SchoolCampusLocation = {
  prefecture: '',
  city: '',
  nearest_stations: [],
};

function isIncompleteCampusLocation(location: SchoolCampusLocation): boolean {
  return !location.prefecture.trim() || !location.city.trim();
}

function duplicateCampusLocation(location: SchoolCampusLocation): SchoolCampusLocation {
  return {
    prefecture: location.prefecture,
    city: location.city,
    nearest_stations: location.nearest_stations ? [...location.nearest_stations] : [],
  };
}

type CampusFocusField = 'prefecture' | 'city';

export default function SchoolEditor({
  initialData,
  onSubmit,
  isSubmitting = false,
  schoolId,
  officialUrlVerified = true,
  officialUrlSource = null,
}: SchoolEditorProps) {
  const [generatingIntro, setGeneratingIntro] = useState(false);
  const [formData, setFormData] = useState<SchoolFormData>({
    name: initialData?.name || '',
    prefecture: initialData?.prefecture || '',
    prefectures: initialData?.prefectures || (initialData?.prefecture ? [initialData.prefecture] : []),
    institution_type: initialData?.institution_type || '',
    campus_locations: initialData?.campus_locations || [],
    slug: initialData?.slug || '',
    intro: initialData?.intro || '',
    highlights: initialData?.highlights || [],
    faq: initialData?.faq || [],
    official_url: initialData?.official_url || '',
    is_public: initialData?.is_public !== undefined ? initialData.is_public : true,
  });

  const [slugAutoGenerated, setSlugAutoGenerated] = useState(false);
  const [campusFocusRequest, setCampusFocusRequest] = useState<{
    index: number;
    field: CampusFocusField;
  } | null>(null);

  useEffect(() => {
    if (!campusFocusRequest) return;
    const elementId =
      campusFocusRequest.field === 'prefecture'
        ? `campus-location-prefecture-${campusFocusRequest.index}`
        : `campus-location-city-${campusFocusRequest.index}`;
    const element = document.getElementById(elementId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'center' });
      element.focus();
    }
    setCampusFocusRequest(null);
  }, [campusFocusRequest, formData.campus_locations]);

  const handleAddCampusLocation = () => {
    setFormData((prev) => ({
      ...prev,
      campus_locations: [{ ...EMPTY_CAMPUS_LOCATION }, ...prev.campus_locations],
    }));
    setCampusFocusRequest({ index: 0, field: 'prefecture' });
  };

  const handleJumpToIncompleteCampus = () => {
    const incompleteIndex = formData.campus_locations.findIndex(isIncompleteCampusLocation);
    if (incompleteIndex === -1) {
      alert('未入力のキャンパス行はありません');
      return;
    }
    const location = formData.campus_locations[incompleteIndex];
    setCampusFocusRequest({
      index: incompleteIndex,
      field: location.prefecture.trim() ? 'city' : 'prefecture',
    });
  };

  const handleDuplicateCampusLocation = (index: number) => {
    setFormData((prev) => {
      const next = [...prev.campus_locations];
      next.splice(index + 1, 0, duplicateCampusLocation(next[index]));
      return { ...prev, campus_locations: next };
    });
    setCampusFocusRequest({ index: index + 1, field: 'city' });
  };

  const campusInputClass =
    'w-full px-2 py-1 text-sm border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500';
  const campusLabelClass = 'block text-xs font-medium text-gray-700 mb-0.5';
  const campusActionClass =
    'px-2 py-1 text-xs border border-gray-300 rounded hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed';

  // 学校名からスラッグを自動生成
  const handleNameChange = (value: string) => {
    setFormData((prev) => {
      const newSlug = !slugAutoGenerated && prev.slug === initialData?.slug
        ? generateSlug(value)
        : prev.slug;
      return {
        ...prev,
        name: value,
        slug: newSlug,
      };
    });
  };

  const handleSlugChange = (value: string) => {
    setFormData((prev) => ({ ...prev, slug: value }));
    setSlugAutoGenerated(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
          学校名 <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="name"
          name="name"
          value={formData.name}
          onChange={(e) => handleNameChange(e.target.value)}
          autoComplete="organization"
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      <div>
        <label htmlFor="prefecture" className="block text-sm font-medium text-gray-700 mb-1">
          都道府県（メイン） <span className="text-red-500">*</span>
        </label>
        <select
          id="prefecture"
          name="prefecture"
          value={formData.prefecture}
          onChange={(e) => {
            const newPrefecture = e.target.value;
            const newPrefectures = formData.prefectures || [];
            // メイン都道府県がprefectures配列に含まれていない場合は追加
            if (newPrefecture && !newPrefectures.includes(newPrefecture)) {
              setFormData((prev) => ({
                ...prev,
                prefecture: newPrefecture,
                prefectures: [...newPrefectures, newPrefecture],
              }));
            } else {
              setFormData((prev) => ({ ...prev, prefecture: newPrefecture }));
            }
          }}
          autoComplete="address-level1"
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="">選択してください</option>
          {prefectures.map((pref) => (
            <option key={pref} value={pref}>
              {pref}
            </option>
          ))}
        </select>
      </div>

      <fieldset>
        <legend className="block text-sm font-medium text-gray-700 mb-1">
          都道府県（複数選択可）
        </legend>
        <div className="space-y-2 max-h-60 overflow-y-auto border border-gray-300 rounded-lg p-3">
          {prefectures.map((pref) => {
            const isSelected = formData.prefectures?.includes(pref) || false;
            return (
              <label key={pref} htmlFor={`prefecture-${pref}`} className="flex items-center">
                <input
                  id={`prefecture-${pref}`}
                  name={`prefecture-${pref}`}
                  type="checkbox"
                  checked={isSelected}
                  onChange={(e) => {
                    const currentPrefectures = formData.prefectures || [];
                    if (e.target.checked) {
                      // 追加
                      const newPrefectures = [...currentPrefectures, pref];
                      setFormData((prev) => ({
                        ...prev,
                        prefectures: newPrefectures,
                        // 最初の都道府県をメインに設定（まだ設定されていない場合）
                        prefecture: prev.prefecture || pref,
                      }));
                    } else {
                      // 削除
                      const newPrefectures = currentPrefectures.filter((p) => p !== pref);
                      setFormData((prev) => ({
                        ...prev,
                        prefectures: newPrefectures,
                        // メイン都道府県が削除された場合、最初の要素をメインに設定
                        prefecture: prev.prefecture === pref && newPrefectures.length > 0
                          ? newPrefectures[0]
                          : prev.prefecture,
                      }));
                    }
                  }}
                  className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                />
                <span className="ml-2 text-sm text-gray-700">{pref}</span>
              </label>
            );
          })}
        </div>
        <p className="mt-1 text-sm text-gray-500">
          選択された都道府県: {formData.prefectures?.length || 0}件
        </p>
      </fieldset>

      <div>
        <label htmlFor="institution_type" className="block text-sm font-medium text-gray-700 mb-1">
          設置区分
        </label>
        <select
          id="institution_type"
          name="institution_type"
          value={formData.institution_type}
          onChange={(e) =>
            setFormData((prev) => ({
              ...prev,
              institution_type: e.target.value as SchoolFormData['institution_type'],
            }))
          }
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="">未設定</option>
          <option value="public">公立通信制高校</option>
          <option value="private">私立通信制高校</option>
          <option value="support">サポート校</option>
        </select>
        <p className="mt-1 text-sm text-gray-500">
          都道府県ページで設置区分ごとの学校表示に使用します。
        </p>
      </div>

      <fieldset>
        <legend className="block text-sm font-medium text-gray-700 mb-2">
          キャンパス所在地（市区町村）
        </legend>
        <p className="text-xs text-gray-500 mb-2">
          都道府県ページや学校詳細で表示します。「追加」は先頭に空行を作ります。類似行は「複製」、入力漏れは「未入力行へ移動」で戻れます。↑↓で順序変更、「都道府県でまとめる」で同じ都道府県を隣接させられます。
        </p>
        <div className="flex flex-wrap items-center justify-between gap-2 mb-2">
          <span className="text-xs text-gray-500">{formData.campus_locations.length}件</span>
          <div className="flex flex-wrap justify-end gap-2">
            <button
              type="button"
              onClick={handleJumpToIncompleteCampus}
              disabled={formData.campus_locations.length === 0}
              className="px-2 py-1 text-xs border border-gray-300 rounded hover:bg-gray-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              未入力行へ移動
            </button>
            <button
              type="button"
              onClick={() =>
                setFormData((prev) => ({
                  ...prev,
                  campus_locations: sortCampusLocationsByPrefecture(
                    prev.campus_locations,
                    prefectures
                  ),
                }))
              }
              disabled={formData.campus_locations.length < 2}
              className="px-2 py-1 text-xs border border-gray-300 rounded hover:bg-gray-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              都道府県でまとめる
            </button>
            <button
              type="button"
              onClick={handleAddCampusLocation}
              className="px-2 py-1 text-xs bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
            >
              追加
            </button>
          </div>
        </div>
        <div className="space-y-1.5">
          {formData.campus_locations.map((location, index) => {
            const [station1, station2] = getCampusNearestStationSlots(location);
            const previousPrefecture =
              index > 0 ? formData.campus_locations[index - 1].prefecture : null;
            const showPrefectureDivider =
              Boolean(location.prefecture) && location.prefecture !== previousPrefecture;
            const isIncomplete = isIncompleteCampusLocation(location);
            return (
              <div key={index}>
                {showPrefectureDivider && (
                  <div className="mb-1 pt-1 text-xs font-semibold text-gray-500">
                    {location.prefecture}
                  </div>
                )}
                <div
                  className={`space-y-1.5 border rounded p-2 ${
                    isIncomplete ? 'border-amber-300 bg-amber-50/40' : 'border-gray-200'
                  }`}
                >
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
                    <div>
                      <label
                        htmlFor={`campus-location-prefecture-${index}`}
                        className={campusLabelClass}
                      >
                        都道府県
                      </label>
                      <select
                        id={`campus-location-prefecture-${index}`}
                        value={location.prefecture}
                        onChange={(e) => {
                          const next = [...formData.campus_locations];
                          next[index] = { ...next[index], prefecture: e.target.value };
                          setFormData((prev) => ({ ...prev, campus_locations: next }));
                        }}
                        className={campusInputClass}
                      >
                        <option value="">選択してください</option>
                        {prefectures.map((pref) => (
                          <option key={pref} value={pref}>
                            {pref}
                          </option>
                        ))}
                      </select>
                    </div>
                    <div>
                      <label htmlFor={`campus-location-city-${index}`} className={campusLabelClass}>
                        市区町村
                      </label>
                      <input
                        id={`campus-location-city-${index}`}
                        type="text"
                        value={location.city}
                        onChange={(e) => {
                          const next = [...formData.campus_locations];
                          next[index] = { ...next[index], city: e.target.value };
                          setFormData((prev) => ({ ...prev, campus_locations: next }));
                        }}
                        placeholder="例: 新宿区"
                        autoComplete="off"
                        className={campusInputClass}
                      />
                    </div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-[1fr_1fr_auto] gap-1.5 items-end">
                    <div>
                      <label
                        htmlFor={`campus-location-station-1-${index}`}
                        className={campusLabelClass}
                      >
                        最寄り駅（1）
                      </label>
                      <input
                        id={`campus-location-station-1-${index}`}
                        type="text"
                        value={station1}
                        onChange={(e) => {
                          const next = [...formData.campus_locations];
                          const [, second] = getCampusNearestStationSlots(next[index]);
                          const stations = [e.target.value, second].filter(
                            (value) => value.trim().length > 0
                          );
                          next[index] = { ...next[index], nearest_stations: stations };
                          setFormData((prev) => ({ ...prev, campus_locations: next }));
                        }}
                        placeholder="例: JR山手線 新宿駅"
                        autoComplete="off"
                        className={campusInputClass}
                      />
                    </div>
                    <div>
                      <label
                        htmlFor={`campus-location-station-2-${index}`}
                        className={campusLabelClass}
                      >
                        最寄り駅（2）
                      </label>
                      <input
                        id={`campus-location-station-2-${index}`}
                        type="text"
                        value={station2}
                        onChange={(e) => {
                          const next = [...formData.campus_locations];
                          const [first] = getCampusNearestStationSlots(next[index]);
                          const stations = [first, e.target.value].filter(
                            (value) => value.trim().length > 0
                          );
                          next[index] = { ...next[index], nearest_stations: stations };
                          setFormData((prev) => ({ ...prev, campus_locations: next }));
                        }}
                        placeholder="例: 丸の内線 新宿三丁目駅（任意）"
                        autoComplete="off"
                        className={campusInputClass}
                      />
                    </div>
                    <div className="flex flex-wrap gap-1">
                      <button
                        type="button"
                        onClick={() =>
                          setFormData((prev) => ({
                            ...prev,
                            campus_locations: moveCampusLocation(prev.campus_locations, index, 'up'),
                          }))
                        }
                        disabled={index === 0}
                        className={campusActionClass}
                        aria-label="上に移動"
                      >
                        ↑
                      </button>
                      <button
                        type="button"
                        onClick={() =>
                          setFormData((prev) => ({
                            ...prev,
                            campus_locations: moveCampusLocation(
                              prev.campus_locations,
                              index,
                              'down'
                            ),
                          }))
                        }
                        disabled={index === formData.campus_locations.length - 1}
                        className={campusActionClass}
                        aria-label="下に移動"
                      >
                        ↓
                      </button>
                      <button
                        type="button"
                        onClick={() => handleDuplicateCampusLocation(index)}
                        className={campusActionClass}
                      >
                        複製
                      </button>
                      <button
                        type="button"
                        onClick={() =>
                          setFormData((prev) => ({
                            ...prev,
                            campus_locations: prev.campus_locations.filter((_, i) => i !== index),
                          }))
                        }
                        className="px-2 py-1 text-xs text-red-600 border border-red-300 rounded hover:bg-red-50"
                      >
                        削除
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
          {formData.campus_locations.length === 0 && (
            <p className="text-xs text-gray-500">所在地は未登録です。追加ボタンで登録できます。</p>
          )}
        </div>
      </fieldset>

      <div>
        <label htmlFor="slug" className="block text-sm font-medium text-gray-700 mb-1">
          スラッグ <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="slug"
          name="slug"
          value={formData.slug}
          onChange={(e) => handleSlugChange(e.target.value)}
          autoComplete="off"
          required
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <p className="mt-1 text-sm text-gray-500">
          URLに使用されるスラッグ（例: school-name）
        </p>
      </div>

      <div>
        <div className="flex items-center justify-between gap-2 mb-1">
          <label htmlFor="intro" className="block text-sm font-medium text-gray-700">
            学校概要（紹介文）
          </label>
          {schoolId && (
            <button
              type="button"
              onClick={async () => {
                if (!confirm('公式サイトを検索して学校概要をAI生成しますか？\n（Perplexity API を使用します）')) {
                  return;
                }
                setGeneratingIntro(true);
                try {
                  const res = await fetch(apiPath(`/api/admin/schools/${schoolId}/intro/generate`), {
                    method: 'POST',
                    credentials: 'include',
                  });
                  if (!res.ok) {
                    const err = await res.json();
                    throw new Error(err.error || '生成に失敗しました');
                  }
                  const data = await res.json();
                  setFormData((prev) => ({ ...prev, intro: data.intro || '' }));
                  alert(`生成しました（使用トークン: ${data.tokensUsed?.total ?? '不明'}）`);
                } catch (e) {
                  alert(e instanceof Error ? e.message : '学校概要の生成に失敗しました');
                } finally {
                  setGeneratingIntro(false);
                }
              }}
              disabled={generatingIntro || isSubmitting}
              className="text-sm px-3 py-1.5 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {generatingIntro ? '生成中...' : 'AIで生成'}
            </button>
          )}
        </div>
        <textarea
          id="intro"
          name="intro"
          value={formData.intro}
          onChange={(e) => setFormData((prev) => ({ ...prev, intro: e.target.value }))}
          rows={6}
          autoComplete="off"
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="学校の紹介文を入力してください（AIで生成ボタンで公式サイトから要約を生成できます）"
        />
      </div>

      <div>
        <label htmlFor="official_url" className="block text-sm font-medium text-gray-700 mb-1">
          公式サイトURL
        </label>
        <input
          type="url"
          id="official_url"
          name="official_url"
          value={formData.official_url || ''}
          onChange={(e) => setFormData((prev) => ({ ...prev, official_url: e.target.value }))}
          placeholder="https://example.ac.jp/"
          autoComplete="url"
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        {formData.official_url && !officialUrlVerified && (
          <div className="mt-2 rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-800">
            <span className="font-semibold">
              {officialUrlSource === 'ai' ? 'AI推定・未確認のURLです' : '未確認のURLです'}
            </span>
            <br />
            このURLが正しい公式サイトか確認し、問題なければそのまま保存してください（保存すると確認済みになります）。誤っていれば正しいURLに直して保存してください。
          </div>
        )}
        <p className="mt-1 text-sm text-gray-500">
          学費・コース情報のAI抽出の起点として使用します（ユーザー向けページには表示されません）。
        </p>
      </div>

      <div>
        <JsonArrayEditor
          label="特徴・推しポイント"
          items={formData.highlights}
          onChange={(items) => setFormData((prev) => ({ ...prev, highlights: items }))}
          placeholder="特徴を入力"
        />
      </div>

      <div>
        <JsonObjectArrayEditor
          label="FAQ"
          items={formData.faq}
          onChange={(items) => setFormData((prev) => ({ ...prev, faq: items }))}
          keyLabel="質問"
          valueLabel="回答"
        />
      </div>

      <div className="flex items-center">
        <input
          type="checkbox"
          id="is_public"
          name="is_public"
          checked={formData.is_public}
          onChange={(e) =>
            setFormData((prev) => ({ ...prev, is_public: e.target.checked }))
          }
          className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
        />
        <label htmlFor="is_public" className="ml-2 text-sm font-medium text-gray-700">
          公開する
        </label>
      </div>

      <div className="flex justify-end gap-4 pt-4">
        <button
          type="submit"
          disabled={isSubmitting}
          className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? '保存中...' : '保存'}
        </button>
      </div>
    </form>
  );
}




